# Generated by Django 4.0.1 on 2022-01-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_profile_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=101, unique=True),
        ),
    ]
