# Generated by Django 4.0.1 on 2022-01-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_profile_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
